FROM golang:1.20-alpine

WORKDIR /app

COPY generated /app/generated
COPY server /app/server

RUN apk add --no-cache git \
    && cd /app/server \
    && go mod edit -replace example.com/mypackage/generated=../generated \
    && go mod tidy \
    && go build -o server .

EXPOSE 50051

CMD ["/app/server/server"]

